version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "distrobox"
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "silverblue"
    schedule:
      interval: "weekly"

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
