name: "Runner setup"
description: "Setup runner required packages for project. Python, Pipenv and set required vars"
inputs:
  context:
    required: true
    description: "Build context folder"
  name:
    required: true
    description: "Name of the image"
  username:
    required: true
    description: "Docker repository username"
  password:
    required: true
    description: "Docker repository password"
runs:
  using: "composite"
  steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d.%H%M%S')"
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        platforms: linux/amd64
        tags: lasercut/${{ inputs.name }}:latest,lasercut/${{ inputs.name }}:${{ steps.date.outputs.date }}
        target: ${{ inputs.name }}
