name: "Test build image"
description: "Test build images for CI"
inputs:
  context:
    required: true
    description: "Build context folder"
  name:
    required: true
    description: "Name of the image"
runs:
  using: "composite"
  steps:
    - name: Set current date as env variable
      run: echo "RELEASE_VERSION=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: false
        platforms: linux/amd64
        tags: lasercut/${{ inputs.name }}:latest,lasercut/${{ inputs.name }}:${{ env.RELEASE_VERSION }}
        target: ${{ inputs.name }}
