name: Release

env:
  SILVERBLUE_IMAGE_NAME: silverblue
  SILVERBLUE_VM_IMAGE_NAME: silverblue-vmware

on:
  push:
    branches:
      - 'master'

jobs:
  build-silverblue:
    name: Build normal silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: silverblue
          push: false
          platforms: linux/amd64
          tags: lasercut/${{ env.SILVERBLUE_IMAGE_NAME }}:latest,lasercut/${{ env.SILVERBLUE_IMAGE_NAME }}:${{ github.ref_name }}
          target: ${{ env.SILVERBLUE_IMAGE_NAME }}

  build-silverblue-vmware:
    name: Build vmware silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: silverblue
          push: false
          platforms: linux/amd64
          tags: lasercut/${{ env.SILVERBLUE_VM_IMAGE_NAME }}:latest,lasercut/${{ env.SILVERBLUE_VM_IMAGE_NAME }}:${{ github.ref_name }}
          target: ${{ env.SILVERBLUE_VM_IMAGE_NAME }}


