name: Release

env:
  CHECKOUT_BRANCH: master

on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 am UTC everyday
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build-silverblue:
    name: Build normal silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Build
        uses: ./.github/actions/build-push-image/
        with:
          context: silverblue
          name: silverblue
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


  build-silverblue-vmware:
    name: Build vmware silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Build
        uses: ./.github/actions/build-push-image/
        with:
          context: silverblue
          name: silverblue-vmware
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-main-apps-distrobox:
    name: Build main apps image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Build
        uses: ./.github/actions/build-push-image/
        with:
          context: distrobox
          name: main-apps-distrobox
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-docker-cli-distrobox:
    name: Build docker cli image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Build
        uses: ./.github/actions/build-push-image/
        with:
          context: distrobox
          name: docker-cli-distrobox
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



