name: Release

env:
  SILVERBLUE_IMAGE_NAME: silverblue
  SILVERBLUE_VM_IMAGE_NAME: silverblue-vmware

on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 am UTC everyday
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build-silverblue:
    name: Build normal silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Build
        uses: ./.github/actions/build-image/
        with:
          context: silverblue
          name: ${{ env.SILVERBLUE_IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


  build-silverblue-vmware:
    name: Build vmware silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Build
        uses: ./.github/actions/build-image/
        with:
          context: silverblue
          name: ${{ env.SILVERBLUE_VM_IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



