name: Release

env:
  SILVERBLUE_IMAGE_NAME: silverblue
  SILVERBLUE_VM_IMAGE_NAME: silverblue-vmware

on:
  push:
    branches:
      - 'master'

jobs:
  build-silverblue:
    name: Build normal silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build-image/
        with:
          context: silverblue
          name: ${{ env.SILVERBLUE_IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


  build-silverblue-vmware:
    name: Build vmware silverblue image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build-image/
        with:
          context: silverblue
          name: ${{ env.SILVERBLUE_VM_IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



